config/routes.rb
Myauth::Application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "home#index"
  resources :users do
    resources :comments
  end
  resources :sessions

  resources :ingredient
  post "search" => "ingredient#search"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :comment, :ingredient_id, :user_id
  belongs_to :user
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :description, :name, :rating
  has_many :comments

	def self.search(search)
		if search
			where('name LIKE ?', "%#{search}%")
		else
			find(:all)
		end
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :first_name, :last_name, :username, :location, :bio

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  has_many :comments
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]  
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(params[:comment])
    @user = User.find(params[:user_id])
    if @comment.save
      @user.comments<< @comment
      flash[:notice] = "Your comment has been saved!"
      redirect_to user_path(params[:user_id])
    else
      flash[:alert] = "There was a problem saving your comment."
      redirect_to new_user_comment_path(params[:user_id])
    end
  end

  def edit
  end

  def update
  end
  
  def index
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController


end

app/controllers/ingredient_controller.rb
class IngredientController < ApplicationController
 
  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(params[:Ingredient])
    @user = User.find(params[:user_id])
    if @ingredient.save
      @user.ingredients << @Ingredient
      flash[:notice] = "Your Ingredient has been saved!"
      redirect_to user_path(params[:user_id])
    else
      flash[:alert] = "There was a problem saving your Ingredient."
      redirect_to new_user_Ingredient_path(params[:user_id])
    end
  end

  def edit
  end

  def update
  end
  
  def index
  	@ingredients=Ingredient.order(:name)

  end

  def show
    @ingredient = Ingredient.find(params[:id])
    @comment = Comment.new
  end

  def search
    @ingredients = Ingredient.search(params[:search])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid credentials."
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new  
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up successfully!"
    else
      flash[:alert] = "Sign up failed."
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = "User updated successfully."
    else
      flash[:alert] = "User could not be updated."
    end
    redirect_to edit_user_path(params[:id])
  end

  def index
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment_form.haml
%h3 New Comment
=form_for @comment, :url => user_comments_path(current_user) do |f|
  -if @comment.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        -for message in @user.errors.full_messages
          %li
            =message
  =f.label :comment
  =f.text_area :comment 
  =f.hidden_field :ingredient_id, :value => params[:id]
  %br
  =f.submit

app/views/comments/edit.haml
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/new.haml
%h1 New Comment
=form_for @comment, :url => user_comments_path do |f|
  -if @comment.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        -for message in @user.errors.full_messages
          %li
            =message
  =f.label :text
  =f.text_area :text
  %br
  =f.submit

app/views/comments/show.haml
=@ingredient.comments

app/views/home/index.haml
.container
%h3 Welcome to...
%h1.title The Quick Guide to Ingredient Labels
%br
%br

.searchbg
  .home-search
    =form_tag "/search" do
      =text_field_tag "search", nil, :placeholder => "Enter your search here"
      =submit_tag "Submit", :class => "btn"


-if !current_user
  .home-login
  %h2 Log in
  =form_tag sessions_path do
    =label_tag :email
    =text_field_tag :email, params[:email], :placeholder => "enter your email"
    =label_tag :password
    =password_field_tag :password
    %br
    =submit_tag "Log in", :class => "btn btn-success"
-else
  -@user = current_user
  .profile
    %h1 
      ="#{@user.first_name} #{@user.last_name}"
    %h3
      =@user.bio if !@user.bio.nil?
    ="@" + @user.username
    %br
    =@user.location
    %br
    %br
    %br
    %br
    %h3 Comments
    %br
    -@user.comments.each do |comment|
      .temp-div{:style => "font-size: 25px"}
        =link_to comment.ingredient.name, ingredient_path(comment)
  
      .temp-div{:style => "font-size: 15px"}
        =comment.comment
     
      .temp-div{:style => "font-size: 11px"}
        =comment.created_at
      %br
      %br

app/views/ingredient/index.haml
%h2 Ingredients A-Z
%br
%br

-@ingredients.each do |ingredient|
	.temp-div{:style => "font-size: 25px"}
		=link_to ingredient.name, ingredient_path(ingredient)
	%br
	=ingredient.description
	%br
	-if ingredient.rating
		Good
	-else
		Bad
	%br
	%br

app/views/ingredient/search.haml
%h1 Ingredients
%br
%br

-if @ingredients.empty?
	No Results Found
-else 
	-@ingredients.each do |ingredient|
		.temp-div{:style => "font-size: 25px"}
			=link_to ingredient.name, ingredient_path(ingredient)
		%br
		=ingredient.description
		%br
		-if ingredient.rating
			Good
		-else
			Bad
		%br
		%br

app/views/ingredient/show.haml
%h1.title 
	=@ingredient.name

=@ingredient.description
%br
%br


%br
-if current_user
	=render "comments/comment_form"
%br
%br
-@ingredient.comments.each do |comment|
	.temp-div{:style => "font-size: 20px"}
		=link_to comment.user.username, "/"
	=comment.comment
	%br
	=comment.created_at
	%br
	%br

app/views/layouts/application.haml
!!!
%html
  %head
    %title Quick Guide
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    .navbar
      .navbar-inner
        .container
          %a.brand{:href => "/"} The Quick Guide
          %ul.nav
            -if current_user
              
              %li
                =link_to "List A-Z", ingredient_index_path
              %li
                =link_to "Log out", log_out_path
            -else
              %li
                =link_to "List A-Z", ingredient_index_path
              %li
                =link_to "Sign up", sign_up_path
              %li
            
          =form_tag "/search", :class => "navbar-form pull-right" do
            =text_field_tag "search", nil, :placeholder => "Enter your search here"
            =submit_tag "Submit", :class => "btn" 
    .maincontainer        
      .row
        .span100.offset0
          -if flash[:notice]
            .notice
              =flash[:notice]
          -if flash[:alert]
            .alert
              =flash[:alert]
      %br
      %br        
      = yield

app/views/users/_form_fields.haml
=form_for @user do |f|
  -if @user.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        -for message in @user.errors.full_messages
          %li
            =message
  =f.label :email
  =f.text_field :email
  =f.label :password
  =f.password_field :password
  =f.label :password_confirmation
  =f.password_field :password_confirmation
  =f.label :first_name
  =f.text_field :first_name
  =f.label :last_name
  =f.text_field :last_name
  =f.label :bio
  =f.text_area :bio, :style => "width: 400px; height: 200px;"
  =f.label :username
  =f.text_field :username
  =f.label :location
  =f.text_field :location
  %br
  %input{:name => "commit", :type => "submit", :value => "Submit", :class => "btn btn-success"}

app/views/users/edit.haml
%h1 Edit Profile
=render "form_fields"

app/views/users/index.haml
-@users.each do |user|
  =link_to "#{user.first_name} #{user.last_name}", user_path(user)
  %br

app/views/users/new.haml
.signup
  %h1 Sign up
  =render "form_fields"

app/views/users/show.haml
.profile
%h1 
  ="#{@user.first_name} #{@user.last_name}"
%h3
  =@user.bio if !@user.bio.nil?
="@" + @user.username
%br
=@user.location
%h3 Comments
-@user.comments.each do |comment|
  =comment.comment
  %br
  .temp-div{:style => "font-size: 11px"}
    =comment.created_at
  %br